### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by hars-singh** [michaelyuancb/general_flow#1]
Hi, Thanks for the great work!!
Could you please open source your code?

Thanks,
Harsh

**Comment by michaelyuancb** [comment]
@hars-singh 
Hi, sorry that I've been busy lately, so I might split it up a few times to sort out and release the code. But I've just released the inference part, which you can try on the provided demo or on your own data

**Comment by michaelyuancb** [comment]
The HOI4D data extraction & training code are also released.

**Comment by michaelyuancb** [comment]
The code is released in April 13,2024. Thanks for your watching.

**Comment by michaelyuancb** [comment]
The code is released in April 13,2024. Thanks for your watching.
